# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b33437f15d852619c5597234684ac250ae666b948a7bb1c1a141419f87c585c7103543dcd5002a642675ed3d58edea3ba70dea97bcdf119df92cedf72decb3

test:
  secret_key_base: d15a5b1f50a160f86b1b799d99e01342e3e133ee61a28b1a6deab8667c5ca651e75b25935a728184209822ac19ddaa24d40986ff1c35cb619344f9a264d9bf01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
